[tool.poetry]
name = "schemas"
version = "0.1.0"
description = "Data schemas and models"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "schemas", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.0"
pyspark = "^3.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
black = "^23.12.0"
ruff = "^0.1.9"
mypy = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
