[tool.poetry]
name = "monitoring"
version = "0.1.0"
description = "Monitoring, metrics, and health checks"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "monitoring", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
prometheus-client = "^0.19.0"
structlog = "^23.2.0"

# Internal dependencies
common = {path = "../common", develop = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
black = "^23.12.0"
ruff = "^0.1.9"
mypy = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
