# Data source configurations
sources:
  stevenblack:
    url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
    format: "hosts"
    category: "ads_trackers"
    update_frequency: "daily"
    description: "StevenBlack's unified hosts file for ads and trackers"

  urlhaus:
    url: "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt"
    format: "adblock"
    category: "malware"
    update_frequency: "12hours"
    description: "URLhaus malware domains"

  1hosts:
    url: "https://badmojr.gitlab.io/1hosts/Lite/adblock.txt"
    format: "adblock"
    category: "ads_trackers"
    update_frequency: "daily"
    description: "1Hosts Lite - ads and trackers"

  adwars:
    url: "https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts"
    format: "hosts"
    category: "ads_trackers"
    update_frequency: "daily"
    description: "Ad-Wars hosts file"
